@startuml settings

start
  :Navigate;
    :Drawer;
    :Settings;

    if (language?) then (Yes)
        :change language;
    else if (theme?) then (Yes)
        :change theme;
    else if (font_size?) then (Yes)
        :Change font size;
    else
        :OK;
    endif
stop
@enduml