@startuml class_diagram

set namespaceSeparator ::

class "about_us.dart::About" {
  {static} +String routeName
  +State<About> createState()
}

"widgets::framework.dart::StatefulWidget" <|-- "about_us.dart::About"

class "about_us.dart::_AboutState" {
  +Widget build()
}

"about_us.dart::About" <|-- "about_us.dart::_AboutState"

class "main.dart::MyApp" {
  +Widget build()
}

"widgets::framework.dart::StatelessWidget" <|-- "main.dart::MyApp"
"main.dart::MyApp" o-- "main.dart::MyHomePage": home
"main.dart::MyApp" o-- "routes.dart::Routes": routes

class "main.dart::MyHomePage" {
  {static} +String routeName
  +String title
  +State<MyHomePage> createState()
}

class "main.dart::_MyHomePageState" {
  -int _selectedIndex
  +List<StatefulWidget> pages
  +Widget build()
  +Container buildMyNavBar()
}

"main.dart::MyHomePage" <|-- "main.dart::_MyHomePageState"

class "settings.dart::SettingsPage" {
  {static} +String routeName
  +State<SettingsPage> createState()
}

"widgets::framework.dart::StatefulWidget" <|-- "settings.dart::SettingsPage"

class "settings.dart::_SettingState" {
  -bool _isDarkMode
  +String dropdownvalue
  +List<String> items
  -double _fontsize
  +bool isDarkMode
  +Widget build()
}

"settings.dart::SettingsPage" <|-- "settings.dart::_SettingState"

class "know_geez.dart::Learn" {
  +State<Learn> createState()
}

"widgets::framework.dart::StatefulWidget" <|-- "know_geez.dart::Learn"

class "know_geez.dart::_LearnState" {
  -String? _data
  -String? _aplhabet
  -String? _numbers
  -String? _example
  -String? _special
  +Future<void> whatGeez()
  +Widget build()
}

"know_geez.dart::Learn" <|-- "know_geez.dart::_LearnState"

class "home.dart::Home" {
  +State<Home> createState()
}

"widgets::framework.dart::StatefulWidget" <|-- "home.dart::Home"

class "home.dart::_HomeState" {
  +TextEditingController textController
  +TextEditingController outputController
  +String dropdownvalue
  +List<String> items
  +void initState()
  +void dispose()
  +Future<void> readJson()
  +Widget build()
}

"home.dart::_HomeState" o-- "widgets::editable_text.dart::TextEditingController"
"home.dart::Home" <|-- "home.dart::_HomeState"

class "routes.dart::Routes" {
  {static} +String about
  {static} +String settings
  {static} +String homepage
}

"routes.dart::Routes" --> "about_us.dart::About"
"routes.dart::Routes" --> "settings.dart::SettingsPage"
"routes.dart::Routes" --> "main.dart::MyHomePage"

"widgets::framework.dart::State" <|-- "widgets::framework.dart::StatefulWidget"
"widgets::framework.dart::State" <|-- "widgets::framework.dart::StatelessWidget"

@enduml