@startuml component_diagram

component "About Us" {
  class "simple_language_translator::about_us.dart::About" as About
  class "simple_language_translator::about_us.dart::_AboutState" as _AboutState
}

component "Main" {
  class "simple_language_translator::main.dart::MyApp" as MyApp
  class "simple_language_translator::main.dart::MyHomePage" as MyHomePage
  class "simple_language_translator::main.dart::_MyHomePageState" as _MyHomePageState
  class "simple_language_translator::routes.dart::Routes" as Routes
}

component "Settings" {
  class "simple_language_translator::settings.dart::SettingsPage" as SettingsPage
  class "simple_language_translator::settings.dart::_SettingState" as _SettingState
}

component "Know Geez" {
  class "simple_language_translator::know_geez.dart::Learn" as Learn
  class "simple_language_translator::know_geez.dart::_LearnState" as _LearnState
}

component "Home" {
  class "simple_language_translator::home.dart::Home" as Home
  class "simple_language_translator::home.dart::_HomeState" as _HomeState
}

MyApp -down-> MyHomePage
MyApp -down-> Routes
MyHomePage -down-> _MyHomePageState
SettingsPage -down-> _SettingState
Learn -down-> _LearnState
Home -down-> _HomeState
About -down-> _AboutState

@enduml